name: 'mobcicd-distribute_to_mobileiron'
description: 'Mobileiron makes distributing your apps to enterprise devices.'
author: 'Productivity Mobile CI/CD'

inputs:
  app_file_path:
    description: 'Artifact path'
    default: 'organization'
    required: true
  app_file_extension:
    description: 'Artifact extension'
    required: true
  build_id:
    description: 'Build ID'
    required: true
  artifact_name:
    description: 'Android or iOS'
    required: True
  workflow_name:
    description: 'GH CICD workflow'
    default: 'deploy-mobileIron-pipeline'
    required: false
  iron_admin_device_space_id:
    description: 'Is a paramter to customize the device-space on Mobile iron where it will be deployed'
    required: false        
  python-version:
    description: 'Python version'
    default: '3.10'
    required: false
   

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Python
      uses: ./../../_actions/current/generic-python
      with:
        python-version: '${{ inputs.ruby-version }}'

    - name: Invoke MobileIron script 
      id: invoke-mobileiron-script
      run: |
        python3 src/main.py call-workflow --workflow "${{ input.workflow_name }}" --repo "$github_repo" --branch "$github_branch" --input "environment=$env,organization=$organization_name,project=$repo_name,buildId=${{ input.build_id}},artifactName=${{ input.artifact_name }},artifactType=${{ input.app_file_extension }},iron_admin_device_space_id=${{ input.iron_admin_device_space_id }}"
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
