name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

inputs:
  app_file_path:
    description: 'Owner type, either user or organization'
    default: 'organization'
    required: true
  app_file_extension:
    description: 'App name as found in the Apps URL in App Center'
    required: true
  build_id:
    description: 'Path to android build binary'
    required: true
  artifact_name:
    description: 'Comma separated list of distribution group names. Default is Collaborators, use * for all distribution groups'
    default: 'Collaborators'
    required: false
  workflow_name:
    description: 'Destination type of distribution destination.'
    default: 'group'
    required: false
  iron_admin_device_space_id:
    description: 'Send email notification about release.'
    default: 'deploy-mobileIron-pipeline'
    required: false        
  python-version:
    description: 'Python version'
    default: '3.10'
    required: false
   

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Python
      uses: ./../../_actions/current/generic-python
      with:
        python-version: '${{ inputs.ruby-version }}'

    - name: Invoke MobileIron script 
      id: invoke-mobileiron-script
      run: |
        python3 src/main.py call-workflow --workflow "${{ input.workflow_name }}" --repo "$github_repo" --branch "$github_branch" --input "environment=$env,organization=$organization_name,project=$repo_name,buildId=${{ input.build_id}},artifactName=${{ input.artifact_name }},artifactType=${{ input.app_file_extension }},iron_admin_device_space_id=${{ input.iron_admin_device_space_id }}"
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
