name: 'Test Action HW'
description: 'Description for CUstom Github action HW'
author: 'MobCICD'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: src/main.js
