name: 'mobcicd-distribute_to_playstore'
description: 'Upload metadata, screenshots and binaries to Google Play (via supply)'
author: 'Productivity Mobile CI/CD'

inputs:
  application_id:
    description: 'package name of the application to use'
    required: true
  json_key:
    description: 'path to a file containing service account JSON, used to authenticate with Google'
    required: true
  path:
    description: 'Path to zipped build on the local filesystem. Either this or url must be specified'
    required: true
  track_deploy:
    description: 'The track of the application to use'
    default: 'beta'
    required: false
  metadata_path:
    description: 'Path to the directory containing the metadata files'
    default: ''
    required: false
  validate_only:
    description: 'Only validate changes with Google Play rather than actually publish'
    default: false
    required: false
  ruby-version:
    description: 'Ruby version'
    default: '3.3'
    required: false
   

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Fastlane
      uses: ./../../_actions/current/generic-fastlane
      with:
        ruby-version: '${{ inputs.ruby-version }}'

    - name: Invoke fastlane playstore lane
      id: invoke-lane
      run: |
        bundle exec fastlane android distribute_to_playstore application_id:"${{ inputs.application_id }}" json_key:"${{ inputs.json_key }}" path:"${{ inputs.path }}" track_deploy:"${{ inputs.track_deploy }}" metadata_path:"${{ inputs.metadata_path }}" validate_only:${{ inputs.validate_only }}
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
