name: 'mobcicd-distribute_to_jfrog'
description: 'Description for Custom Github action HW'
author: 'Productivity Mobile CI/CD'

inputs:
  pattern:
    description: 'Pattern files to be uploaded to artifactory'
    required: true
  repo:
    description: 'Artifactory repo to put the file in'
    required: true
  repo_path:
    description: 'Path to deploy within the repo, including filename'
    required: true
  ruby-version:
    description: 'Ruby version'
    default: '3.3'
    required: false
   

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Fastlane
      uses: ./../../_actions/current/generic-fastlane
      with:
        ruby-version: '${{ inputs.ruby-version }}'

    - name: Invoke fastlane jfrog lane
      id: invoke-lane
      run: |
        bundle exec fastlane distribute_to_jfrog pattern:"${{ inputs.pattern }}" repo:"${{ inputs.repo }}" repo_path:"${{ inputs.repo_path }}"
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
