name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

inputs:
  app_id:
    description: 'App identification'
    required: true
  apk_path:
    description: 'Path Apk'
    required: true
  submit_for_review:
    description: 'False by default'
    required: false      
  ruby-version:
    description: 'Ruby version'
    default: '3.3'
    required: false
   

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Fastlane
      uses: ./../../_actions/current/generic-fastlane
      with:
        ruby-version: '${{ inputs.ruby-version }}'

    - name: Invoke fastlane Huawei lane
      id: invoke-lane
      run: |
        ls -la
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
