name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: 'composite'
  steps:
    - name: Set utils action path
      id: set-utils-path
      run: |
        action_path=${{ github.action_path }}
        utils_action_path=$(dirname $action_path)/utils
        fastlane_action_path=$(dirname $action_path)/utils/fastlane
        echo "UTILS_ACTION_PATH=${utils_action_path}" >> $GITHUB_ENV
        echo "FASTLANE_ACTION_PATH=${fastlane_action_path}" >> $GITHUB_ENV
      shell: bash

    - name: Init fastlane
      id: invoke-appcente-lane
      run: |
        bundle install 
        bundle exec fastlane lanes
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}
      
     


#############################
