name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

inputs:
  path:
    description: 'Path to zipped build on the local filesystem. Either this or url must be specified'
    required: true
  public_key:
    description: 'If not provided, a new app will be created. If provided, the existing build will be overwritten	'
    required: true
  api_host:
    description: 'Appetize API host'
    required: false
  platform:
    description: 'Platform. Either ios or android'
    default: 'Collaborators'
    required: false
  note:
    description: 'Notes you wish to add to the uploaded app'
    required: false
  ruby-version:
    description: 'Ruby version'
    default: '3.3'
    required: false

runs:
  using: 'composite'
  steps:

    - name: Symlink current Actions repo
      run: ln -s /home/runner/work/_actions/$GH_ACTION_REPO/$GH_ACTION_REF/  /home/runner/work/_actions/current  
      shell: bash
      env:
        GH_ACTION_REPO: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}      

    - name: Call Generic action to Fastlane
      uses: ./../../_actions/current/generic-fastlane
      with:
        ruby-version: '${{ inputs.ruby-version }}'

    - name: Invoke fastlane appcenter lane
      id: invoke-appcenter-lane
      run: |
        ls -la
      shell: bash
      working-directory: ${{ env.FASTLANE_ACTION_PATH }}

#############################
