name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: 'composite'
  steps:
    - name: Set utils action path
      id: set-utils-path
      run: |
        action_path=${{ github.action_path }}
        utils_action_path=$(dirname $action_path)/utils
        echo "UTILS_ACTION_PATH=${utils_action_path}" >> $GITHUB_ENV
      shell: bash

    - id: added-comment
      run: |
        echo {{ env.UTILS_ACTION_PATH }}
      shell: bash
      
     


#############################
