name: 'Test Action HW'
description: 'Description for Custom Github action HW'
author: 'MobCICD'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: 'composite'
  steps:
    - name: Generate app installation token
      id: generate-token
      run: |
        action_path=${{ github.action_path }}
        action_repo_path=$(dirname $action_path)
        echo "ACTION_REPO_PATH=${action_repo_path}" >> $GITHUB_ENV
      shell: bash

    - id: added-comment
      run: |
        echo {{ env.ACTION_REPO_PATH }}
      shell: bash
      working-directory: '{{ env.ACTION_REPO_PATH }}'
     


#############################
